version: "3.8"
services:
  database:
    build:
      context: ../
      dockerfile: Dockerfile.ls-db
    ports:
      - "3453:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 30
      interval: 5s

  lobby-service:
    build:
      context: ../
      dockerfile: Dockerfile.ls
    ports:
      - "34172:34172"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:34172/api/online || exit 1
      timeout: 5s
      retries: 20
      interval: 5s

  server:
    build:
      context: ../../
      dockerfile: setup/Dockerfile.server
    ports:
      - "33402:33402"
    depends_on:
      lobby-service:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:33402/api/online || exit 1
      timeout: 5s
      retries: 20
      interval: 5s

  client:
    build:
      context: ../
      dockerfile: Dockerfile.client
    volumes:
      - ../../client:/usr/share/nginx/html/
    ports:
      - "36104:80"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      timeout: 5s
      retries: 20
      interval: 5s
