
name: Backend Build

on:
  push:
    branches: [master]
    paths:
      - 'server/**'
      - 'client/**'
      - 'linters/**'
      - '.github/**'

  pull_request:
    branches: [master]
    paths:
      - 'server/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./server
      run: mvn -B clean package --file pom.xml
    - name: Run tests
      working-directory: ./server
      run: mvn test
